<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FiTrackerV2.BLL\FiTrackerV2.BLL.csproj" />
    <ProjectReference Include="..\FiTrackerV2.Domain\FiTrackerV2.Domain.csproj" />
  </ItemGroup>

</Project>
